### ISSUE TITLE
There are two font assets in my projects but only one was preloaded when using this plugin

### ISSUE THREAD

**Issue by zhijunzhou** [sn-satyendra/webpack-font-preload-plugin#13]
First of all, thank you for creating such an excellent plugin!

There is a problem in the following code:
```
const newNodes = this.createNodeFromHtml(document, links);
  if (newNodes && newNodes.length > 0) {
    newNodes.forEach((n) => {
      parent.insertBefore(n, insertBeforeTag);
    });
  }
```

The type of `newNodes` should be an [HTMLLinkElement](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLLinkElement) Collection instead of an Array. So we cannot use the `forEach` method to iterate `newNodes`.

**Comment by sn-satyendra** [comment]
Hi @zhijunzhou, I wanted to understand more about the issue.

Won't the type of `newNodes` be `NodeList` ? 
[container.childNodes](https://github.com/sn-satyendra/webpack-font-preload-plugin/blob/master/src/index.js#L169) should return a [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes) which is created by `jsdom`. Also jsdom [supports forEach](https://github.com/jsdom/jsdom/issues/1709) on NodeList.

**Comment by zhijunzhou** [comment]
@sn-satyendra I take a screenshot below:
![image](https://user-images.githubusercontent.com/15681407/111739759-8e730b00-88be-11eb-859e-d27188d5d9cb.png)

Yes, the type of `newNodes` should be `NodeList`. And the output Line #110 is a `NodeList` contains two `HTMLLinkElement`. But  in the `forEach` block, the Line #114 just only output one `HTMLLinkElement`. 

Maybe this is a bug from `jsdom`😄

**Comment by zhijunzhou** [comment]
My quick solution is to add a `Array.from(newNodes)` wrapper, and the output is correct as we want! 
![screenshot-20210319-144053](https://user-images.githubusercontent.com/15681407/111741649-c596eb80-88c1-11eb-9061-ac2a52cf4aa1.png)

**Comment by sn-satyendra** [comment]
Thanks for providing the details @zhijunzhou. 

I was able to reproduce the issue. In my case it was not quite noticeable as I was using other font formats as well and did not notice the missing types. It seems like `newNodes` is a reference instead of copy which is causing its length to change (need to confirm this although).

**Comment by sn-satyendra** [comment]
Fixed by https://github.com/sn-satyendra/webpack-font-preload-plugin/pull/14.
