### ISSUE TITLE
JSDOM is missing

### ISSUE THREAD

**Issue by vojty** [sn-satyendra/webpack-font-preload-plugin#15]
Hello,

I've tried to use this plugin, it kinda works but I've noticed 2 things

1. JSDOM should be listed at least in `peerDependencies` - plugin immediately crashes if jsdom is not present
2. Plugin doesn't recognize magic `publicPath: 'auto'` see https://github.com/jantimon/html-webpack-plugin/issues/1514 and generates invalid `<link>` tags

I've fixed it with:
```
function getPublicPath(outputOptions) {
  if (!outputOptions) {
    return ''
  }

  const { publicPath } = outputOptions
  if (publicPath === 'auto') {
    return ''
  }
  return publicPath
}
```
but I'm not really sure whether it's correct solution or not...

**Comment by sn-satyendra** [comment]
@vojty thanks for reporting the issue. You are right, the `jsdom` should be there in `peerDependencies`.

Will check on `publicPath: 'auto'` and get back.
