### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by PodaruDragos** [sn-satyendra/webpack-font-preload-plugin#24]
Are there any plans to add typescript type definitions ?

Having a `webpack.config.ts` file will result in errors for not providing a type definition for this.

**Comment by PodaruDragos** [comment]
> @PodaruDragos yes, that is planned and should be available in some days.

Thanks for the answer, feel free to close this if you want or just tag me here when the types are available.

**Comment by sn-satyendra** [comment]
The types are available with 1.4.0.

**Comment by PodaruDragos** [comment]
hey @sn-satyendra. I think the type definitions are not correct.

`import FontPreloadPlugin from 'webpack-font-preload-plugin';`

```
  new FontPreloadPlugin({
    index: 'index.html'
  }),
```

```
(alias) new FontPreloadPlugin(options?: FontPreloadPlugin.Options | undefined): FontPreloadPlugin
import FontPreloadPlugin
Type 'WebpackFontPreloadPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
  Property 'apply' is missing in type 'WebpackFontPreloadPlugin' but required in type 'WebpackPluginInstance'.ts(2322)
types.d.ts(12147, 2): 'apply' is declared here.
```

**Comment by sn-satyendra** [comment]
> hey @sn-satyendra. I think the type definitions are not correct.
> 
> `import FontPreloadPlugin from 'webpack-font-preload-plugin';`
> 
> ```
>   new FontPreloadPlugin({
>     index: 'index.html'
>   }),
> ```
> 
>  ```
> (alias) new FontPreloadPlugin(options?: FontPreloadPlugin.Options | undefined): FontPreloadPlugin
> import FontPreloadPlugin
> Type 'WebpackFontPreloadPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
>   Property 'apply' is missing in type 'WebpackFontPreloadPlugin' but required in type 'WebpackPluginInstance'.ts(2322)
> types.d.ts(12147, 2): 'apply' is declared here.
> ```
> 
> It seems that `apply` is missing from the type definition.
> 
> It should be like so
> 
> ```
> declare class WebpackFontPreloadPlugin {
>   constructor(options?: WebpackFontPreloadPlugin.Options);
> 
>   /**
>    * Webpack font preload plugin options to modify the default configuration.
>    */
>   options?: WebpackFontPreloadPlugin.Options;
> 
>   /**
>   * Apply the plugin
>   */
>   apply(compiler: Compiler): void;
> }
> ```

@PodaruDragos My bad. Can you try out once with `1.4.1-beta.0` if all looks good ?

**Comment by PodaruDragos** [comment]
yes seems to be ok.
