### ISSUE TITLE
Can't filter files in order to preload only 1 or 2 more flagged files

### ISSUE THREAD

**Issue by NeOMakinG** [sn-satyendra/webpack-font-preload-plugin#26]
Hey,

We want to preload only one asset instead of every woff2 fonts for example, is there a solution? Overwise I still extended your project by flagging the asset name (if it contains preload for example, it will be preloaded), would it be merged fast and release?

**Comment by sn-satyendra** [comment]
@NeOMakinG there is no direct way to specify this but you can use the [replaceCallback](https://github.com/sn-satyendra/webpack-font-preload-plugin#replacecallback) option which provides the consuming app to fully customise where and how the link tags are placed in the generated index.html.
```js
new FontPreloadPlugin({
  ...
  replaceCallback: ({ indexSource, linksAsString }) => {
    // `indexSource` is the raw source string of your html which contains a templating placeholder
    // like `{{{links}}}` somewhere in head (its just a placeholder and anything can be used).
    // `linksAsString` are the link tags generated as part of build process. If you need you can filter 
    // out the links which are not required to be preloaded. 
    return indexSource.replace("{{{links}}}", linksAsString);
  },
});
```

**Comment by NeOMakinG** [comment]
> @NeOMakinG there is no direct way to specify this but you can use the [replaceCallback](https://github.com/sn-satyendra/webpack-font-preload-plugin#replacecallback) option which provides the consuming app to fully customise where and how the link tags are placed in the generated index.html.
> 
> ```js
> new FontPreloadPlugin({
>   ...
>   replaceCallback: ({ indexSource, linksAsString }) => {
>     // `indexSource` is the raw source string of your html which contains a templating placeholder
>     // like `{{{links}}}` somewhere in head (its just a placeholder and anything can be used).
>     // `linksAsString` are the link tags generated as part of build process. If you need you can filter 
>     // out the links which are not required to be preloaded. 
>     return indexSource.replace("{{{links}}}", linksAsString);
>   },
> });
> ```

So I would use a regex to remove every other link tags than the one I'm interested to? Looks like it's not a really maintainable way to me...

Would you agree if I contribute to add the feature and release it?

**Comment by sn-satyendra** [comment]
> > @NeOMakinG there is no direct way to specify this but you can use the [replaceCallback](https://github.com/sn-satyendra/webpack-font-preload-plugin#replacecallback) option which provides the consuming app to fully customise where and how the link tags are placed in the generated index.html.
> > ```js
> > new FontPreloadPlugin({
> >   ...
> >   replaceCallback: ({ indexSource, linksAsString }) => {
> >     // `indexSource` is the raw source string of your html which contains a templating placeholder
> >     // like `{{{links}}}` somewhere in head (its just a placeholder and anything can be used).
> >     // `linksAsString` are the link tags generated as part of build process. If you need you can filter 
> >     // out the links which are not required to be preloaded. 
> >     return indexSource.replace("{{{links}}}", linksAsString);
> >   },
> > });
> > ```
> 
> So I would use a regex to remove every other link tags than the one I'm interested to? Looks like it's not a really maintainable way to me...
> 
> Would you agree if I contribute to add the feature and release it?

Regex would be tricky here but jsdom could be used to parse the link to object. 

Contributions are welcome. What's the approach you would take?

**Comment by NeOMakinG** [comment]
Currently in the project I did add an options called `flag` where you can put a string, with `default` : `preload`, so you are able to add `preload` to assets name, and these assets will be preloaded, wdyt?

**Comment by NeOMakinG** [comment]
> Currently in the project I did add an options called `flag` where you can put a string, with `default` : `preload`, so you are able to add `preload` to assets name, and these assets will be preloaded, wdyt?

Couldn't find a better way because in your plugin scope, you only have hashed names :/

**Comment by sn-satyendra** [comment]
> > Currently in the project I did add an options called `flag` where you can put a string, with `default` : `preload`, so you are able to add `preload` to assets name, and these assets will be preloaded, wdyt?
> 
> Couldn't find a better way because in your plugin scope, you only have hashed names :/

Can we call this option as `filter` (instead of `flag`) ?  It can be a regex or string which allows to filter specific assets.

**Comment by NeOMakinG** [comment]
> > > Currently in the project I did add an options called `flag` where you can put a string, with `default` : `preload`, so you are able to add `preload` to assets name, and these assets will be preloaded, wdyt?
> > 
> > 
> > Couldn't find a better way because in your plugin scope, you only have hashed names :/
> 
> Can we call this option as `filter` (instead of `flag`) ? It can be a regex or string which allows to filter specific assets.
> 
> ```js
> addFonts() {
>   ...
>   if (this.isFontAsset(asset) && this.isFiltered(asset)) {
>     strLink += this.getLinkTag(asset, publicPath);
>   }
>   ...
> },
> isFiltered(name) {
>   if (name instanceOf RegExp) {
>     // Check that the asset name matches the filter regex.
>     return this.options.filter.test(name);
>   }
>   // Check if the asset name contains the specified filter string.
>   return name.replace(this.options.filter, '') !== name;
> }
> ```

Yeah of course we can!

**Comment by NeOMakinG** [comment]
Oh damn, you did it! I was planing to do it today :)

Thanks @sn-satyendra 👍
