### ISSUE TITLE
publicPath can be defined as '' but this plugin won't work with it

### ISSUE THREAD

**Issue by NeOMakinG** [sn-satyendra/webpack-font-preload-plugin#31]
Because of this condition: https://github.com/sn-satyendra/webpack-font-preload-plugin/blob/master/src/index.js#L57

If we set the publicPath to '' (it can happen sometime, I managed to make it works by setting this path only to one specific loader), it won't work because the condition won't be valid, it can be changed to a more precise condition in order to accept it!

**Comment by sn-satyendra** [comment]
@NeOMakinG yes this was a miss during types addition. #30 should fix it.
