### ISSUE TITLE
JSDOM serialize generates invalid HTML with triple mustache syntax

### ISSUE THREAD

**Issue by christoph-bessei** [sn-satyendra/webpack-font-preload-plugin#8]
**Problem:**

We use this plugin in combination with Vue.js (SSR), so our `index.html` contains triple mustache placeholders for unescpaed HTML: https://ssr.vuejs.org/guide/#using-a-page-template

index.html:
```html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no,maximum-scale=1.0">
    <!-- Meta tag placeholders, filled during SSR -->
    {{{ metaTags }}}
</head>
<body>
<!--vue-ssr-outlet-->
</body>
</html>
```
Sadly `JSDOM.serialize` (or parse?) can't handle the triple mustache syntax and generates broken HTML.

result.html (duplicate meta tags, head and body):
```html
<!DOCTYPE html>
<html lang="de">
<head>
    <link rel="preload" href="/fonts/PRELOAD_INJECTED_BY-webpack-font-preload-plugin.woff2" as="font" crossorigin="">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no,maximum-scale=1.0">
    <!-- Meta tag placeholders, filled during SSR -->
    <link rel="stylesheet" href="injected-css-by-vue-js-ssr.css">
    </head>
<body>

<title data-meta="1">INJECTED TITLE</title>
<meta data-meta="1" name="description" content="INJECTED DESCRIPTION">
</head>
<body>
<title data-meta="1">INJECTED TITLE</title>
<meta data-meta="1" name="description" content="INJECTED DESCRIPTION">

<!-- INJECTED VUE.JS CONTENT AND SCRIPTS-->
</body></html>
```
Since `<head>{{{meta}}}</head>` is already invalid HTML, the behaviour of JSDOM is probably correct. At the same time it's pretty common to have template variables inside `index.html` during build time.

**Possible solutions:**
- Inject the `link` tags with regular expressions/string manipulation, ... (probably not easy to handle all edge cases)
- Add a `placeholder` option. The content (e.g. `###PRELOAD_FONTS###`) is directly replaced with the `link` tags - The plugin user would be responsible for a unique placeholder in this case.
- Add a `replaceCallback` option. The callback should get 2 parameters (1. content of `indexFile`, 2. the `link` tags) and the return value would be used as the ouput (`result.html` in my case)

**Comment by sn-satyendra** [comment]
Thanks @christoph-bessei for reporting the issue. I think the 3rd solution mentioned by you should provide more flexibility in terms of handling this behaviour and more such cases.
